jd_scripts:
  image: sanbing666/scripts
  # 配置服务器资源约束。此例子中服务被限制为使用内存不超过200M以及cpu不超过0.2（单核的20%）
  # 经过实际测试，建议不低于200M
  # deploy:
  #   resources:
  #     limits:
  #       cpus: '0.2'
  #       memory: 200M
  container_name: jd_scripts
  restart: always
  #扫码映射端口
  ports:
    - 6789:6789
  volumes:
    - ./logs:/scripts/logs
  tty: true
  # 因为更换仓库地址可能git pull的dns解析不到，可以在配置追加hosts
  extra_hosts:
    - "gitee.com:180.97.125.228"
    - "github.com:13.229.188.59"
    - "raw.githubusercontent.com:151.101.228.133"
  environment:
    #脚本更新仓库地址，配置了会切换到对应的地址
    - REPO_URL=git@github.com:sanbing666/scripts.git
    # 注意环境变量填写值的时候一律不需要引号（""或者''）下面这些只是示例，根据自己的需求增加删除
    # 使用自定义定任务覆盖默认任务，上面volumes挂载之后这里配置对应的文件名，和自定义文件使用方式为overwrite
    #- CUSTOM_LIST_FILE=my_crontab_list.sh
    #- CUSTOM_LIST_MERGE_TYPE=overwrite
    #jd cookies
    # 例: JD_COOKIE=pt_key=XXX;pt_pin=XXX;
    # 例（多账号）: JD_COOKIE=pt_key=XXX;pt_pin=XXX;&pt_key=XXX;pt_pin=XXX;&pt_key=XXX;pt_pin=XXX;
    - JD_COOKIE=
    
    
    #京东appUA&京喜
    - JD_USER_AGENT=
    - JX_USER_AGENT=
    #微信server酱通知
    - PUSH_KEY=
    #Bark App通知
    - BARK_PUSH=
    #telegram机器人通知
    - TG_BOT_TOKEN=
    - TG_USER_ID=
    #钉钉机器人通知
    - DD_BOT_TOKEN=
    - DD_BOT_SECRET=
    #企业微信机器人通知
    - QYWX_AM=
    
    #####脚本互助码变量区#####
    #单容器多账号自动互助
    - ENABLE_AUTO_HELP=true
    #京东种豆得豆
    - PLANT_BEAN_SHARECODES=
    #宠汪汪赛跑自己账号内部互助
    - JOY_RUN_HELP_MYSELF=true
    #取关店铺和商品
    - UN_SUBSCRIBES=0&100
    
    #####脚本变量区#####
    #前端扫码默认不运行
    - QRcookie_ENABLE=
    #前端扫码企业微信通知
    - QR_QYWX_AM=
    #东东超市商品兑换与并发执行
    - coinToBeans = '京豆包'
    - blueCoin_Cc = True
    #不执行的脚本
    - DO_NOT_RUN_SCRIPTS=
    #财富岛热气球挂机
    - CFD_LOOP_ENABLE=
    #京东试用是否运行
    - JD_TRY=
    #京东试用不执行的账号
    - DONOT_TRY_ACCOUNT=
    #早起赢现金
    - morningScPins=
    #愤怒的锦鲤
    - kois=
    #愤怒的现金
    - cashHelpPins=
    #赚30元
    - earn30Pins=
    #发财大赢家助力
    - dyjHelpPins=
    #京喜单独开团
    - jxgc_kaituan=
    

    #如果设置了 RANDOM_DELAY_MAX ，则会启用随机延迟功能，延迟随机 0 到 RANDOM_DELAY_MAX-1 秒。如果不设置此项，则不使用延迟。
    #并不是所有的脚本都会被启用延迟，因为有一些脚本需要整点触发。延迟的目的有两个，1是降低抢占cpu资源几率，2是降低检查风险（主要是1）
    #填写数字，单位为秒，比如写为 RANDOM_DELAY_MAX=30  就是随机产生0到29之间的一个秒数，执行延迟的意思。
    - RANDOM_DELAY_MAX=120
    
    #####任务推送区#####
    #东东萌宠推送
    - PET_NOTIFY_CONTROL=false
    #东东农场推送
    - FRUIT_NOTIFY_CONTROL=false
    #京东领现金推送
    - CASH_NOTIFY_CONTROL=false
    #点点券推送
    - DDQ_NOTIFY_CONTROL=false
    #京东赚赚小程序推送
    - JDZZ_NOTIFY_CONTROL=false
    #京东摇钱树推送开关
    - MONEYTREE_NOTIFY_CONTROL=false
    #宠汪汪兑换京豆推送开关
    - JD_JOY_REWARD_NOTIFY=false
    #宠汪汪赛跑推送
    - JOY_RUN_NOTIFY=true
    #东东超市推送
    - MARKET_REWARD_NOTIFY=false
    #京喜财富岛推送
    - CFD_NOTIFY_CONTROL=true
